"""Contract for the reusable, PURE source-recording splitter (sv-lds.20.1).

``cut_segments`` carves ONE long source recording into per-affirmation clips
using cut points shaped like ``data/refuge_split.yaml`` (each entry
``{"id": str, "start": float}``, seconds from the top of the file, ORDERED
ascending by start). Segment ``i`` spans ``[start_i, start_{i+1})``; the LAST
segment spans ``[start_last, end-of-file]``. Each clip is written to
``output_dir/{id}.wav`` as 16-bit PCM WAV.

These tests exercise the splitter against a SYNTHETIC sine source generated by
ffmpeg's ``lavfi`` — NOT the real (uncommitted, sensitive) Refuge.mp3 — so the
contract is testable in isolation with no DB, no HTTP, and no private audio.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest
import soundfile as sf

from sharedvoice.audio.segment import cut_segments

FFMPEG = shutil.which("ffmpeg") or "ffmpeg"

# ffmpeg re-encoding a synthetic source is not always frame-exact, so we allow
# a generous tolerance on measured clip durations.
TOL_SECONDS = 0.3
SOURCE_DURATION = 12.0


def _make_sine_wav(path: Path, duration: float = SOURCE_DURATION) -> Path:
    """Generate a ``duration``-second 440 Hz sine WAV at ``path`` via ffmpeg."""
    subprocess.run(
        [
            FFMPEG,
            "-y",
            "-f",
            "lavfi",
            "-i",
            f"sine=frequency=440:duration={duration}",
            "-ar",
            "44100",
            str(path),
        ],
        check=True,
        capture_output=True,
    )
    return path


@pytest.fixture
def source_wav(tmp_path: Path) -> Path:
    """A synthetic 12s sine WAV standing in for the long source recording."""
    return _make_sine_wav(tmp_path / "source.wav")


def _duration(path: Path) -> float:
    return sf.info(str(path)).duration


def test_cut_segments_carves_ordered_clips(source_wav: Path, tmp_path: Path):
    """Three ordered cut points over a 12s source yield three ~4s clips.

    ``a`` and ``b`` are bounded by the NEXT start; ``c`` (the last) runs to EOF.
    """
    output_dir = tmp_path / "out"
    output_dir.mkdir()

    segments = [
        {"id": "a", "start": 0.0},
        {"id": "b", "start": 4.0},
        {"id": "c", "start": 8.0},
    ]

    result = cut_segments(source_wav, segments, output_dir)

    # Exactly one output per segment id, keyed by id.
    assert set(result.keys()) == {"a", "b", "c"}

    for seg_id, out_path in result.items():
        out_path = Path(out_path)
        assert out_path.exists(), f"{seg_id}: expected clip at {out_path}"
        assert out_path.name == f"{seg_id}.wav"
        assert out_path.parent == output_dir
        # Contract pins 16-bit PCM WAV output.
        assert sf.info(str(out_path)).subtype == "PCM_16"

    # [0,4), [4,8), [8,12] → each ~4s (last bounded by EOF, not a next-start).
    assert _duration(Path(result["a"])) == pytest.approx(4.0, abs=TOL_SECONDS)
    assert _duration(Path(result["b"])) == pytest.approx(4.0, abs=TOL_SECONDS)
    assert _duration(Path(result["c"])) == pytest.approx(4.0, abs=TOL_SECONDS)


def test_single_segment_spans_whole_source(source_wav: Path, tmp_path: Path):
    """A lone segment has no next-start to bound it, so it runs to EOF (~12s)."""
    output_dir = tmp_path / "out"
    output_dir.mkdir()

    segments = [{"id": "only", "start": 0.0}]

    result = cut_segments(source_wav, segments, output_dir)

    assert set(result.keys()) == {"only"}
    out_path = Path(result["only"])
    assert out_path.exists()
    assert out_path.name == "only.wav"
    assert _duration(out_path) == pytest.approx(SOURCE_DURATION, abs=TOL_SECONDS)


def test_missing_source_raises(tmp_path: Path):
    """A nonexistent source must raise SOME catchable exception rather than
    silently emitting empty/garbage output.

    The exact exception type is the implementer's choice (e.g.
    ``FileNotFoundError``, ``subprocess.CalledProcessError`` from a failed
    ffmpeg run, or a module-specific error) — this test pins only that the
    failure is surfaced, not swallowed.
    """
    output_dir = tmp_path / "out"
    output_dir.mkdir()

    segments = [{"id": "a", "start": 0.0}]

    with pytest.raises(Exception):
        cut_segments(tmp_path / "does-not-exist.wav", segments, output_dir)
